using System.Reflection;

namespace Reaper.SourceGenerator;

public static class StaticGeneration
{
    public static AssemblyName AssemblyName = Assembly.GetExecutingAssembly().GetName();
    public static string AssemblyFullName = AssemblyName.FullName;
    public static string AssemblyVersion = AssemblyName.Version.ToString();
    
    public const string Attribute = """
                                    namespace Reaper {
                                        public class ReaperExts {
                                            public string Test() => "Test";
                                        }
                                    }
                                    """;

    public const string FileHeader = """
                                     //------------------------------------------------------------------------------
                                     // <auto-generated>
                                     //     This code was generated by a tool.
                                     //
                                     //     Changes to this file may cause incorrect behavior and will be lost if
                                     //     the code is regenerated.
                                     // </auto-generated>
                                     //------------------------------------------------------------------------------

                                     #nullable enable
                                     """;

    public static string CodeInterceptorAttribute = $$"""
                                                      namespace System.Runtime.CompilerServices
                                                      {
                                                          [System.CodeDom.Compiler.GeneratedCodeAttribute("{{AssemblyFullName}}", "{{AssemblyVersion}}")]
                                                          [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
                                                          file sealed class InterceptsLocationAttribute : Attribute
                                                          {
                                                              public InterceptsLocationAttribute(string filePath, int line, int column)
                                                              {
                                                              }
                                                          }
                                                      }
                                                      """;

    public static string GeneratedCodeAttribute = $"[System.CodeDom.Compiler.GeneratedCodeAttribute(\"{AssemblyFullName}\", \"{AssemblyVersion}\")]";
}